version: "3.7"
services:
  rmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    expose: 
      - "5672"
  api:
    image: restapi:latest
    environment:
      - RMQ_URL=rmq:5672
      - RMQ_UNAME=guest
      - RMQ_PWD=guest
      - RMQ_QNAME=TestQueue
    ports:
      - "8080:8080"